# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Cache testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COVERITY_SERVER_URL: http://coverity.synopsys-alliances.com

    steps:
    - uses: actions/checkout@v2
    - name: Cache Coverity Analysis
      id: cache-coverity
      uses: actions/cache@v2
      with:
        path: |
           coverity/
           idir/
        key: ubuntu-coverity-1

    - name: Download Coverity
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
         mkdir coverity/
         cd coverity/
         curl --user gautam:${{ secrets.COVERITY_PASSPHRASE }} -o license.dat $COVERITY_SERVER_URL/downloadFile.htm?fn=license.dat

    - name: ls to see
      run: ls -als && cd coverity/ && ls -als
